go_to_action/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from .views import MovieListView, NewMovieView, MovieDetailView, EmailSenderView

urlpatterns = patterns('',
	url(r'^new/$', NewMovieView.as_view(), name='movie_new'),
	url(r'^(?P<pk>\d+)/$', MovieDetailView.as_view(), name='movie_detail'),
	url(r'^(?P<pk>\d+)/edit/$', NewMovieView.as_view(), name='movie_edit'),
	url(r'^(?P<pk>\d+)/email/$', EmailSenderView.as_view(), name='send_email'),
	url(r'^', MovieListView.as_view(), name='movie_list'),
)

review_action/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns
from .views import ReviewHandlerView, EmailSenderView

urlpatterns = patterns('',
    (r'^email', EmailSenderView.as_view()),
    (r'^', ReviewHandlerView.as_view()),
)

urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
	url(r'^review_action/', include('review_action.urls', app_name='review_action')),
	url(r'^go_to_action/', include('go_to_action.urls', app_name='go_to_action', namespace='go_to_action')),
	# url(r'^', include('review_action.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

go_to_action/models.py
# -*- coding: utf-8 -*-
from google.appengine.ext import ndb


class Movie(ndb.Model):
	title = ndb.StringProperty(required=True, default='No Title')

review_action/models.py
# -*- coding: utf-8 -*-
from google.appengine.ext import ndb


class Review(ndb.Model):
	rating_value = ndb.IntegerProperty(required=True)
	review_body = ndb.TextProperty(required=False)

go_to_action/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Movie

class MovieForm(forms.Form):
	u'''映画'''
	title = forms.CharField(required=True)

go_to_action/views.py
# -*- coding: utf-8 -*-
import logging
from urlparse import urlparse

from google.appengine.api import mail
from google.appengine.api import users

from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseServerError
from django.shortcuts import render, redirect
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.template import Context, loader
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import View
from django.views.generic.list import ListView
from django.utils.decorators import method_decorator

from . import APP_LABEL
from .models import Movie
from .forms import MovieForm


logger = logging.getLogger(__name__)


class EmailSenderView(View):
	template_name = APP_LABEL + '/send_mail.html'

	def get(self, request, pk=None):
		# require users to be logged in to send emails
		user = users.get_current_user()
		if not user:
			return redirect(users.create_login_url(request.path))

		obj = Movie.get_by_id(int(pk))
		logger.warn(pk)
		if not obj:
			return redirect('go_to_action:movie_list')

		email = user.email()
		logger.warn(request.path)

		# the review url corresponds to the App Engine app url
		pr = urlparse(request.build_absolute_uri())
		app_name = request.resolver_match.app_name
		url = '%s://%s/%s' % (pr.scheme, pr.netloc, app_name)

		# load the email template and replace the placeholder with the review url
		template_values = {
				'url': url,
				'pk': pk,
				'title': obj.title,
				}
		email_body = loader.render_to_string(APP_LABEL + '/mail_template.html', Context(template_values))

		message = mail.EmailMessage(
				sender=email,
				to=email,
				subject='See the detail of movie \'%s\'' % obj.title,
				html=email_body)
		template_values = {
				'email': email,
				}

		try:
			message.send()
			return render(request, self.template_name, template_values)
		except:
			return HttpResponseServerError()


class MovieListView(View):
	template_name = APP_LABEL + '/movie_list.html'

	def get(self, request):
		template_values = {
				'movies': Movie.query(),
				}

		return render(request, self.template_name, template_values)

	def post(self, request):
		title = request.POST.get('title')
		movie = Movie(title=title)
		movie.put()

		template_values = {
				'movies': Movie.query(),
				}
		return render(request, self.template_name, template_values)


class NewMovieView(View):
	template_name = APP_LABEL + '/movie_edit.html'

	def get(self, request):
		form = MovieForm()
		template_values = {
				'app_name': request.resolver_match.app_name,
				'form': form,
				}

		return render(request, self.template_name, template_values)


class MovieDetailView(View):
	template_name = APP_LABEL + '/movie_detail.html'

	def get(self, request, pk=None):
		template_values = {
				'movie': Movie.get_by_id(int(pk)),
				}

		return render(request, self.template_name, template_values)

review_action/views.py
# -*- coding: utf-8 -*-
import logging
from urlparse import urlparse

from google.appengine.api import mail
from google.appengine.api import users

from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseServerError
from django.shortcuts import render, redirect
from django.template import Context, loader
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import View
from django.utils.decorators import method_decorator

from .models import Review


logger = logging.getLogger(__name__)


class EmailSenderView(View):

	def get(self, request):
		# require users to be logged in to send emails
		user = users.get_current_user()
		if not user:
			return redirect(users.create_login_url(request.path))

		email = user.email()
		logger.warn(request.path)

		# the review url corresponds to the App Engine app url
		pr = urlparse(request.build_absolute_uri())
		app_name = request.resolver_match.app_name
		review_url = '%s://%s/%s/' % (pr.scheme, pr.netloc, app_name)

		# load the email template and replace the placeholder with the review url
		template = loader.get_template('mail_template.html')
		template_values = {
				'review_url': review_url,
				}
		email_body = loader.render_to_string('mail_template.html', Context(template_values))

		message = mail.EmailMessage(
				sender=email,
				to=email,
				subject='Please review Google Cafe',
				html=email_body)

		try:
			message.send()
			return HttpResponse('OK')
		except:
			return HttpResponseServerError()


class ReviewHandlerView(View):

	def get(self, request):
		# retrieve up to 1000 reviews from the Datastore
		reviews = Review.query().fetch(1000)

		if not reviews:
			return HttpResponse('No reviews')

		total = 0
		count = len(reviews)
		response = HttpResponse()

		for r in reviews:
			total += r.rating_value
			review_body = r.review_body or 'No feedback'
			response.write('%d/5 - %s<br />' % (r.rating_value, review_body))

		response.write('<br />')
		response.write('%d reviews - Average rating %.2f/5' % (count, total / float(count)))

		return response

	def post(self, request):
		rating_value = request.POST.get('review.reviewRating.ratingValue')
		review_body = request.POST.get('review.reviewBody')

		# the numeric rating is required
		if not rating_value:
			return HttpResponseBadRequest()

		# insert the review into the Datastore
		review = Review(rating_value=int(rating_value), review_body=review_body)
		review.put()

		return HttpResponse('OK')

	@method_decorator(csrf_exempt)
	def dispatch(self, *args, **kwargs):
		return super(ReviewHandlerView, self).dispatch(*args, **kwargs)

libs/bootstrapform/templates/bootstrapform/field.html
{% load bootstrap %}

<div class="form-group{% if field.errors %} has-error{% endif %}">
    {% if field|is_checkbox %}
        <div class="{{ classes.single_value }}">
            <div class="checkbox">
                {% if field.auto_id %}
                    <label {% if field.field.required and form.required_css_class %}class="{{ form.required_css_class }}"{% endif %}>
                        {{ field }} <span>{{ field.label }}</span>
                    </label>
                {% endif %}
                {% for error in field.errors %}
                    <span class="help-block {{ form.error_css_class }}">{{ error }}</span>
                {% endfor %}

                {% if field.help_text %}
                    <p class="help-block">
                        {{ field.help_text|safe }}
                    </p>
                {% endif %}
            </div>
        </div>
    {% elif field|is_radio %}
        {% if field.auto_id %}
            <label class="control-label {{ classes.label }} {% if field.field.required %}{{ form.required_css_class }}{% endif %}">{{ field.label }}</label>
        {% endif %}
        <div class="{{ classes.value }}">
            {% for choice in field %}
                <div class="radio">
                    <label>
                        {{ choice.tag }}
                        {{ choice.choice_label }}
                    </label>
                </div>
            {% endfor %}

            {% for error in field.errors %}
                <span class="help-block {{ form.error_css_class }}">{{ error }}</span>
            {% endfor %}

            {% if field.help_text %}
            <p class="help-block">
                {{ field.help_text|safe }}
            </p>
            {% endif %}
        </div>
    {% else %}
        {% if field.auto_id %}
            <label class="control-label {{ classes.label }} {% if field.field.required %}{{ form.required_css_class }}{% endif %}" for="{{ field.auto_id }}">{{ field.label }}</label>
        {% endif %}

        <div class="{{ classes.value }} {% if field|is_multiple_checkbox %}multiple-checkbox{% endif %}">
            {{ field }}

            {% for error in field.errors %}
                <span class="help-block {{ form.error_css_class }}">{{ error }}</span>
                {% endfor %}

            {% if field.help_text %}
                <p class="help-block">
                    {{ field.help_text|safe }}
                </p>
            {% endif %}
        </div>
    {% endif %}
</div>

libs/bootstrapform/templates/bootstrapform/form.html
{% if form.non_field_errors %}
    <div class="alert alert-danger">
        <a class="close" data-dismiss="alert">&times;</a>
        {% for non_field_error in form.non_field_errors %}
             {{ non_field_error }}
        {% endfor %}
    </div>
{% endif %}

{% for field in form.hidden_fields %}
    {{ field }}
{% endfor %}

{% for field in form.visible_fields %}
    {% include 'bootstrapform/field.html' %}
{% endfor %}

libs/bootstrapform/templates/bootstrapform/formset.html
{{ formset.management_form }}

{% for form in formset %}

  {% include "bootstrapform/form.html" with form=form %}

{% endfor %}

review_action/templates/mail_template.html
<html>
<head>
	<title>Did you enjoy Google Cafe?</title>
</head>
<body>
	<script type="application/ld+json">
    {
      "@context":               "http://schema.org",
      "@type":                  "Restaurant",
      "name":                   "Google Cafe",
      "action": {
        "@type":                "ReviewAction",
        "review": {
          "@type":              "Review",
          "reviewRating": {
            "@type":            "Rating",
            "bestRating":       "5",
            "worstRating":      "1"
          }
        },
        "handler": {
          "@type":              "HttpActionHandler",
          "url":                "{{ review_url }}",
          "encoding": {
            "url":              "http://schema.org/Encoding/UrlEncoded"
          },
          "method":             "http://schema.org/HttpRequestMethod/POST",
          "requiredProperty": {
            "@type":            "Property",
            "name":             "review.reviewRating.ratingValue"
          },
          "optionalProperty": {
            "@type":            "Property",
            "name":             "review.reviewBody"
          }
        }
      }
    }
	</script>
	<p>
	Dear John, please rate Google Cafe between 1 and 5 stars and, optionally, add a text comment.
	</p>
</body>
</html>

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
	<head>
		<meta charset="UTF-8">
		<title>{% block title %}My books{% endblock %}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
		<script src="{% static 'js/jquery-1.11.1.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		{% block extrahead %}{% endblock %}
	</head>
	<body>
		<div class="container">
			{% block content %}
			{{ content }}
			{% endblock %}
		</div>
	</body>
</html>

templates/go_to_action/mail_template.html
<html>
<head>
	<title>Go-to Action</title>
</head>
<body>
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "EmailMessage",
  "action": {
    "@type": "ViewAction",
	"url": "{{ url }}/{{ pk }}/",
    "name": "Watch movie"
  },
  "description": "See the detail of movie '{{ title }}'"
}
</script>
	<p>
	Click the "Watch movie" button and see the detail of movie
	</p>
</body>
</html>

templates/go_to_action/movie_detail.html
{% extends "base.html" %}

{% block title %}Movie Detail{% endblock title %}

{% block extrahead %}
<style>
table {
	margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
<h3 class="page-header">Movie Detail</h3>
<table class="table table-hover table-condensed">
	<tbody>
		<tr>
			<td>ID</th>
			<td>{{ movie.key.id }}</td>
		</tr>
		<tr>
			<td>Title</td>
			<td>{{ movie.title }}</td>
		</tr>
	</tbody>
</table>
{% endblock content %}

templates/go_to_action/movie_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}Edit Movie{% endblock title %}

{% block content %}
{% if movie_id %}
<h3 class="page-header">Edit Movie</h3>
<form action="{{app_name}}/movies/{{movie_id}}" method="put" class="form-horizontal" role="form">
{% else %}
<h3 class="page-header">New Movie</h3>
<form action="/{{app_name}}/movies/" method="post" class="form-horizontal" role="form">
{% endif %}
	{% csrf_token %}
	{{ form|bootstrap_horizontal }}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-primary">送信</button>
		</div>
	</div>
</form>
{% endblock content %}

templates/go_to_action/movie_list.html
{% extends "base.html" %}

{% block title %}Movie List{% endblock title %}

{% block extrahead %}
<style>
table {
	margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
<h3 class="page-header">Movie List</h3>
<a href="{% url 'go_to_action:movie_new' %}" class="btn btn-default btn-sm">New</a>
<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>ID</th>
			<th>Title</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		{% for movie in movies %}
		<tr>
			<td>{{ movie.key.id }}</td>
			<td>{{ movie.title }}</td>
			<td>
				<a href="{% url 'go_to_action:movie_detail' pk=movie.key.id %}" class="btn btn-default btn-sm">See</a>
				<!-- TODO: implement this -->
				<a href="{% url 'go_to_action:movie_list' %}" class="btn btn-danger btn-sm">Delete</a>
				<!-- -->
				<a href="{% url 'go_to_action:send_email' pk=movie.key.id %}" class="btn btn-primary btn-sm">
					<span class="glyphicon glyphicon-envelope"></span> Send Email
				</a>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>

{% endblock content %}

templates/go_to_action/send_mail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap %}

{% block extrahead %}
<style>
body {
	margin-top: 8px;
}
</style>
<link href="{% static 'css/jumbotron-narrow.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}Email sent{% endblock title %}
{% block content %}
<div class="container">
	<div class="jumbotron">
		<h2>Complete!</h2>
		<p class="lead">Email was sent to <b> {{ email }} </b> successfully.</p>
		<p><a href="{% url 'go_to_action:movie_list' %}" class="btn btn-lg btn-success">Back to movie list</a></p>
	</div>
</div>
{% endblock content %}